// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: tracking.proto

/*
Package __ is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package __

import (
	"context"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/known/emptypb"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = metadata.Join

func request_TrackingByContainerNumber_TrackByContainerNumber_0(ctx context.Context, marshaler runtime.Marshaler, client TrackingByContainerNumberClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq Request
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.TrackByContainerNumber(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_TrackingByContainerNumber_TrackByContainerNumber_0(ctx context.Context, marshaler runtime.Marshaler, server TrackingByContainerNumberServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq Request
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.TrackByContainerNumber(ctx, &protoReq)
	return msg, metadata, err

}

func request_TrackingByBillNumber_TrackByBillNumber_0(ctx context.Context, marshaler runtime.Marshaler, client TrackingByBillNumberClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq Request
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.TrackByBillNumber(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_TrackingByBillNumber_TrackByBillNumber_0(ctx context.Context, marshaler runtime.Marshaler, server TrackingByBillNumberServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq Request
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.TrackByBillNumber(ctx, &protoReq)
	return msg, metadata, err

}

func request_ScacService_GetContainerScac_0(ctx context.Context, marshaler runtime.Marshaler, client ScacServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq emptypb.Empty
	var metadata runtime.ServerMetadata

	msg, err := client.GetContainerScac(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_ScacService_GetContainerScac_0(ctx context.Context, marshaler runtime.Marshaler, server ScacServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq emptypb.Empty
	var metadata runtime.ServerMetadata

	msg, err := server.GetContainerScac(ctx, &protoReq)
	return msg, metadata, err

}

func request_ScacService_GetBillScac_0(ctx context.Context, marshaler runtime.Marshaler, client ScacServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq emptypb.Empty
	var metadata runtime.ServerMetadata

	msg, err := client.GetBillScac(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_ScacService_GetBillScac_0(ctx context.Context, marshaler runtime.Marshaler, server ScacServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq emptypb.Empty
	var metadata runtime.ServerMetadata

	msg, err := server.GetBillScac(ctx, &protoReq)
	return msg, metadata, err

}

// RegisterTrackingByContainerNumberHandlerServer registers the http handlers for service TrackingByContainerNumber to "mux".
// UnaryRPC     :call TrackingByContainerNumberServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterTrackingByContainerNumberHandlerFromEndpoint instead.
func RegisterTrackingByContainerNumberHandlerServer(ctx context.Context, mux *runtime.ServeMux, server TrackingByContainerNumberServer) error {

	mux.Handle("POST", pattern_TrackingByContainerNumber_TrackByContainerNumber_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/tracking.TrackingByContainerNumber/TrackByContainerNumber", runtime.WithHTTPPathPattern("/tracking/container"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_TrackingByContainerNumber_TrackByContainerNumber_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_TrackingByContainerNumber_TrackByContainerNumber_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

// RegisterTrackingByBillNumberHandlerServer registers the http handlers for service TrackingByBillNumber to "mux".
// UnaryRPC     :call TrackingByBillNumberServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterTrackingByBillNumberHandlerFromEndpoint instead.
func RegisterTrackingByBillNumberHandlerServer(ctx context.Context, mux *runtime.ServeMux, server TrackingByBillNumberServer) error {

	mux.Handle("POST", pattern_TrackingByBillNumber_TrackByBillNumber_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/tracking.TrackingByBillNumber/TrackByBillNumber", runtime.WithHTTPPathPattern("/tracking/bill"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_TrackingByBillNumber_TrackByBillNumber_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_TrackingByBillNumber_TrackByBillNumber_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

// RegisterScacServiceHandlerServer registers the http handlers for service ScacService to "mux".
// UnaryRPC     :call ScacServiceServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterScacServiceHandlerFromEndpoint instead.
func RegisterScacServiceHandlerServer(ctx context.Context, mux *runtime.ServeMux, server ScacServiceServer) error {

	mux.Handle("GET", pattern_ScacService_GetContainerScac_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/tracking.ScacService/GetContainerScac", runtime.WithHTTPPathPattern("/scac/container"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_ScacService_GetContainerScac_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_ScacService_GetContainerScac_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("GET", pattern_ScacService_GetBillScac_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/tracking.ScacService/GetBillScac", runtime.WithHTTPPathPattern("/scac/bills"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_ScacService_GetBillScac_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_ScacService_GetBillScac_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

// RegisterTrackingByContainerNumberHandlerFromEndpoint is same as RegisterTrackingByContainerNumberHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterTrackingByContainerNumberHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.Dial(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterTrackingByContainerNumberHandler(ctx, mux, conn)
}

// RegisterTrackingByContainerNumberHandler registers the http handlers for service TrackingByContainerNumber to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterTrackingByContainerNumberHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterTrackingByContainerNumberHandlerClient(ctx, mux, NewTrackingByContainerNumberClient(conn))
}

// RegisterTrackingByContainerNumberHandlerClient registers the http handlers for service TrackingByContainerNumber
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "TrackingByContainerNumberClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "TrackingByContainerNumberClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "TrackingByContainerNumberClient" to call the correct interceptors.
func RegisterTrackingByContainerNumberHandlerClient(ctx context.Context, mux *runtime.ServeMux, client TrackingByContainerNumberClient) error {

	mux.Handle("POST", pattern_TrackingByContainerNumber_TrackByContainerNumber_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/tracking.TrackingByContainerNumber/TrackByContainerNumber", runtime.WithHTTPPathPattern("/tracking/container"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_TrackingByContainerNumber_TrackByContainerNumber_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_TrackingByContainerNumber_TrackByContainerNumber_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_TrackingByContainerNumber_TrackByContainerNumber_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"tracking", "container"}, ""))
)

var (
	forward_TrackingByContainerNumber_TrackByContainerNumber_0 = runtime.ForwardResponseMessage
)

// RegisterTrackingByBillNumberHandlerFromEndpoint is same as RegisterTrackingByBillNumberHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterTrackingByBillNumberHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.Dial(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterTrackingByBillNumberHandler(ctx, mux, conn)
}

// RegisterTrackingByBillNumberHandler registers the http handlers for service TrackingByBillNumber to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterTrackingByBillNumberHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterTrackingByBillNumberHandlerClient(ctx, mux, NewTrackingByBillNumberClient(conn))
}

// RegisterTrackingByBillNumberHandlerClient registers the http handlers for service TrackingByBillNumber
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "TrackingByBillNumberClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "TrackingByBillNumberClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "TrackingByBillNumberClient" to call the correct interceptors.
func RegisterTrackingByBillNumberHandlerClient(ctx context.Context, mux *runtime.ServeMux, client TrackingByBillNumberClient) error {

	mux.Handle("POST", pattern_TrackingByBillNumber_TrackByBillNumber_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/tracking.TrackingByBillNumber/TrackByBillNumber", runtime.WithHTTPPathPattern("/tracking/bill"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_TrackingByBillNumber_TrackByBillNumber_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_TrackingByBillNumber_TrackByBillNumber_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_TrackingByBillNumber_TrackByBillNumber_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"tracking", "bill"}, ""))
)

var (
	forward_TrackingByBillNumber_TrackByBillNumber_0 = runtime.ForwardResponseMessage
)

// RegisterScacServiceHandlerFromEndpoint is same as RegisterScacServiceHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterScacServiceHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.Dial(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterScacServiceHandler(ctx, mux, conn)
}

// RegisterScacServiceHandler registers the http handlers for service ScacService to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterScacServiceHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterScacServiceHandlerClient(ctx, mux, NewScacServiceClient(conn))
}

// RegisterScacServiceHandlerClient registers the http handlers for service ScacService
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "ScacServiceClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "ScacServiceClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "ScacServiceClient" to call the correct interceptors.
func RegisterScacServiceHandlerClient(ctx context.Context, mux *runtime.ServeMux, client ScacServiceClient) error {

	mux.Handle("GET", pattern_ScacService_GetContainerScac_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/tracking.ScacService/GetContainerScac", runtime.WithHTTPPathPattern("/scac/container"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_ScacService_GetContainerScac_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_ScacService_GetContainerScac_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("GET", pattern_ScacService_GetBillScac_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/tracking.ScacService/GetBillScac", runtime.WithHTTPPathPattern("/scac/bills"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_ScacService_GetBillScac_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_ScacService_GetBillScac_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_ScacService_GetContainerScac_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"scac", "container"}, ""))

	pattern_ScacService_GetBillScac_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"scac", "bills"}, ""))
)

var (
	forward_ScacService_GetContainerScac_0 = runtime.ForwardResponseMessage

	forward_ScacService_GetBillScac_0 = runtime.ForwardResponseMessage
)
